### PR TITLE
Fixes #40 for introduced sbatch issues

### LINKED ISSUE #40: Script fails when trying to run from a different directory.
### Describe the bug
The `pipeline.sh` script fails when running it from a different directory.

#### v1.0.0
Directory structure used when encountering issue:
```
vip
|- vip-1.0.0
  |- pipeline.sh
  |- pipeline_0_preprocess.sh
  \- etc.
\- out
```
1. Make sure you are in the `vip` folder.
2. `sbatch --constraint=tmp01 vip-1.0.0/pipeline.sh -i vip-1.0.0/test/data/test.vcf -o out/test1.vcf`

This results in the following error:
```bash
$ cat vip.err
/var/spool/slurmd/job307828/slurm_script: line 195: ./pipeline_0_preprocess.sh: No such file or directory
```

#### master (584504842e2daa9d54f93195ebb5017ba4a1fe46)
Using the current master (commit: 584504842e2daa9d54f93195ebb5017ba4a1fe46) results in a slightly different `vip.err` (as it does not stop after the first error), but has the same problem:
```
$ cat vip.err
/var/spool/slurmd/job308894/slurm_script: line 12: utils/header.sh: No such file or directory
sh: ./pipeline_preprocess.sh: No such file or directory
sh: ./pipeline_annotate.sh: No such file or directory
sh: ./pipeline_filter.sh: No such file or directory
mv: cannot stat ‘/groups/umcg-gcc/tmp01/umcg-svandenhoek/vip/vip-master-2020-09-08/out3/out_pipeline_out/step2_filter//out.vcf’: No such file or directory
sh: ./pipeline_report.sh: No such file or directory
cp: cannot stat ‘/groups/umcg-gcc/tmp01/umcg-svandenhoek/vip/vip-master-2020-09-08/out3/out_pipeline_out/step4_report//out.html’: No such file or directory
```

### Expected behavior
Script runs independent of the directory from which it was executed.

### Additional context

A solution such as seen [here](https://github.com/molgenis/vibe/blob/719403ed21c0e471adae86fa9ab33c233bebc319/database/GenerateDatabase.sh#L33) might fix this. However, using `cd` to go to the script directory might break user-input paths if these are relative paths. Pre-pending the `${BASE_PATH}` to the used scripts might therefore be a better solution.

### PR DESCRIPTION
**Pull request by svandenhoek**
Tested with:
```
sbatch --qos=priority --constraint=tmp01 --output=../outA/vip.out --error=../outA/vip.err pipeline.sh -i test/data/test.vcf -o ../outA/out.vcf
sbatch --qos=priority --constraint=tmp01 --output=outB/vip.out --error=outB/vip.err vip/pipeline.sh -i vip/test/data/test.vcf -o outB/out.vcf
sh vip/pipeline.sh -i vip/test/data/test.vcf -o outC/out.vcf
```

### CODE REVIEW

**Comment by svandenhoek** [comment]
Fix for #40.

File: pipeline.sh [hunk 1]
```diff
@@ -214,7 +222,7 @@ fi
 if [ ! -z "${FORCE}" ]; then
 	PREPROCESS_ARGS+=" -f"
 fi
-sh "${SCRIPT_DIR}"/pipeline_preprocess.sh ${PREPROCESS_ARGS}
```
Comment (dennishendriksen) [inline pipeline.sh:217]: I prefer SCRIPT_DIR to SCRIPT_SUBMIT_DIR, since your not submitting only makes sense in a job execution context.

File: pipeline.sh [hunk 2]
```diff
@@ -9,8 +9,16 @@
...
 #SBATCH --get-user-env=L60
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-source "${SCRIPT_DIR}"/utils/header.sh
+# Retrieve original directory of submitted script.
+if [ -n "$SLURM_JOB_ID" ] ; then # If Slurm job.
+  SCRIPT_SUBMIT_DIR=$(scontrol show job "$SLURM_JOBID" | awk -F= '/Command=/{print $2}')
+  SCRIPT_SUBMIT_DIR="${SCRIPT_SUBMIT_DIR%% *}" # Removes anything starting at first space (so keep script path).
+else
+  SCRIPT_SUBMIT_DIR=$(realpath "$0")
```
Comment (dennishendriksen) [inline pipeline.sh:17]: Could you motivate your change from `="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"` to `
=$(realpath "$0")`?

File: pipeline.sh [hunk 3]
```diff
@@ -9,8 +9,16 @@
 #SBATCH --export=NONE
 #SBATCH --get-user-env=L60
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-source "${SCRIPT_DIR}"/utils/header.sh
+# Retrieve original directory of submitted script.
```
Comment (dennishendriksen) [inline pipeline.sh:12]: Comment is a bit confusing: if you execute the shell script then you are not submitting the script.

File: pipeline.sh [hunk 4]
```diff
@@ -9,8 +9,16 @@
...
+if [ -n "$SLURM_JOB_ID" ] ; then # If Slurm job.
+  SCRIPT_SUBMIT_DIR=$(scontrol show job "$SLURM_JOBID" | awk -F= '/Command=/{print $2}')
+  SCRIPT_SUBMIT_DIR="${SCRIPT_SUBMIT_DIR%% *}" # Removes anything starting at first space (so keep script path).
+else
+  SCRIPT_SUBMIT_DIR=$(realpath "$0")
+fi
+readonly SCRIPT_SUBMIT_DIR="${SCRIPT_SUBMIT_DIR%/*}" # Removes "/<scriptname>".
```
Comment (dennishendriksen) [inline pipeline.sh:19]: Could be part of the if clause if you don't make the change mentioned in the previous comment.

**Review by dennishendriksen — APPROVED** [review]

File: pipeline.sh (hunk 1 above)
Comment (svandenhoek) [reply pipeline.sh]: Suggested change was implemented.

File: pipeline.sh (hunk 2 above)
Comment (svandenhoek) [reply pipeline.sh]: To cite `info coreutils 'realpath invocation'`:
> 18.5 'realpath': Print the resolved file name.
> \==============================================
> 
> 'realpath' expands all symbolic links and resolves references to '/./',
'/../' and extra '/' characters.

So it's a cleaner solution code-wise (as it was created for these use-cases) that should also be able to resolve symbolic links (haven't tested this though). As it's part of [GNU coreutils](https://www.gnu.org/software/coreutils/), most modern Linux distro's should also support it by default (an otherwise installation should be rather easy).

There is a downside in that MacOS does not support it by default, though this is also the case for many other things such as `wget`. This can be fixed by using a package manager such as MacPorts or HomeBrew. For example, using MacPorts one can do `sudo port install coreutils` to install GNU coreutils and then add `export PATH=/opt/local/libexec/gnubin/:$PATH` to the `.bash_profile` to make GNU coreutils the default (instead of the BSD commands MacOS normally uses). Though again, this isn't a `realpath` specific issue but rather a MacOS issue in general.

File: pipeline.sh (hunk 4 above)
Comment (svandenhoek) [reply pipeline.sh]: It was left outside the if clause as both cases have this part in common. One could use `dirname` instead and add it to both the if & else if less lines is preferred.

File: pipeline.sh (hunk 2 above)
Comment (svandenhoek) [reply pipeline.sh]: Sidenote: `realpath` is already used elsewhere in the script as well: https://github.com/molgenis/vip/blob/cf3954bc05ffff460eb7af7c64b724a03a54e252/pipeline.sh#L84
